version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_celery: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: backend_production_django
    depends_on:
      - postgres
      - redis
    # https://stackoverflow.com/questions/67714136/file-writing-failing-in-docker-production-environment
    volumes:
      - production_celery:/app/celery_data:z
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backend_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: backend_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:30:30"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: backend_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: backend_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: backend_production_flower
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/production/node/Dockerfile
    image: frontend_production_node
    container_name: node
    depends_on:
      - django
    volumes:
      - .:/app/:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/frontend/node_modules
    command: npm start
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"
